### PR TITLE
Fixes project cards being white

### PR DESCRIPTION
**Pull request by ZeWaka**
Before:
image
After:
image

### CODE REVIEW

**Comment by poychang** [comment]
I can not replicate this issue. Anyone has this problem too?

**Comment by ZeWaka** [comment]
> I can not replicate this issue. Anyone has this problem too?
Hmm, I'm on Microsoft Edge/Chromium, and the version in the Edge Addon zone is 2 patch versions out of date (1.1.18), but I don't think that'd be the issue. 
Looking at my local inspection, the lines I modified here were added by the extension, and removing them resolved my issue. I haven't been able to get the local extension building done just yet, haven't had too much time.

I'm also encountering a similar issue with my notifications as of recent, looking like the following:
image

**Comment by IamCathal** [comment]
The notification issue was fixed in https://github.com/poychang/github-dark-theme/pull/310 so you should see that change soo.

I'm on chrome and the project cards have their correct dark background colors at the moment

**Comment by poychang** [comment]
Currently Microsoft Edge not support CD. So...I'll submit manually this version.

**Comment by ZeWaka** [comment]
Resolved by switching to the Chrome version of the extension. Should be noted that problems like these will persist for users who use the Edge version, however.

**Pull request closed without merging**
