### PR TITLE
fix(branches overview table): gray out footer

### PR DESCRIPTION
**Pull request by ivanvoznyakovsky**
|before|after|
|-|-|
|Screenshot 2019-04-08 23 16 35|Screenshot 2019-04-08 23 15 56|

### CODE REVIEW

**Comment by poychang** [comment]
Thanks for your contribution 👍

**Comment by ivanvoznyakovsky** [comment]
@poychang for some reason these changes did not get into the store. can rebuild and redeploy?

**Comment by poychang** [comment]
It’s because the last 2 PR use the same version number, that cause deploy failed. 
I’ll fix that later. Thanks :)

**Comment by ivanvoznyakovsky** [comment]
ok. thnx for details. I'll take it into account in my next PRs

**Pull request merged**
